const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
async function main(){
 const window={};vm.runInNewContext(fs.readFileSync('prism/vendor/app-24-keywordlab.js','utf8'),{window,clearTimeout,setTimeout});
 const a=window.PRISM_APP_PARTS[0]();a._authHeaders=()=>({});a.reviewer='검수자';
 assert.equal(a.kwReady(),false);a.kwChooseMode('single');a.kwSlots[0]={model:'solar',version_id:'v1'};
 assert.equal(a.kwReady(),false);a.kwLead='한국은행이 금리를 인하했다';a.kwEntities='한국은행';assert.equal(a.kwReady(),true);
 a.kwModel(a.kwSlots[0],'gpt');assert.equal(a.kwSlots[0].version_id,'');
 let sent;a._afetch=async(url,opt)=>{sent=JSON.parse(opt.body);return{json:async()=>({ok:true})}};
 await a.kwRequest('',{action:'review'});assert.equal(sent.reviewer,'검수자');
 a.kwRunData={cells:{'key:A':{id:'key:A',status:'done',review_revision:2,refined:{keywords:[{text:'한국은행',kind:'single'}]},reviews:[],final:null}}};
 a.kwCatalog={versions:[],gold:[]};a.kwOpenReview({key:'key'},{label:'A'});assert.equal(a.kwReview.expected_revision,2);assert.equal(a.kwReview.judgments[0].verdict,'');assert.equal(a.kwTab,'run');
 a.kwRunId='run';a.kwOpenRun=async()=>{a.kwRunData.cells['key:A'].review_revision=3};
 await a.kwSaveReview();assert.equal(sent.expected_revision,2);assert.equal(a.kwReview.expected_revision,3);
 a._afetch=async()=>({json:async()=>({ok:false,error:'저장 충돌'})});await a.kwSaveReview();assert.equal(a.kwError,'저장 충돌');assert.equal(a.kwBusy,false);

 const b=window.PRISM_APP_PARTS[0]();
 assert.deepEqual(Array.from(b.kwTabs,t=>t[0]),['run','prompts']);
 b.kwCatalog={runs:[{id:'one',n:1},{id:'many',n:3}],versions:[],default_rules:'기본 규칙'};
 b.kwChooseMode('compare');assert.equal(b.kwCount,2);
 b.kwCount=3;b.kwSlots=[{model:'m1',version_id:'v1'},{model:'m2',version_id:'v2'},{model:'m3',version_id:'v3'}];
 b.kwSource='reuse';b.kwReuse='many';assert.equal(b.kwReady(),true);
 b.kwSlots[2].version_id='v2';assert.equal(b.kwReady(),false);b.kwSlots[2].version_id='v3';
 b.kwChooseMode('single');assert.equal(b.kwCount,1);assert.equal(b.kwReuse,'many');assert.equal(b.kwReady(),true);
 b.kwSlots[0].version_id='v1';b.kwSource='hash';b.kwHashes='a,a';assert.equal(b.kwReady(),false);b.kwHashes='a,b';assert.equal(b.kwReady(),true);
 b.kwSource='sample';b.kwSample=20;b.kwRequest=async(q,data)=>{sent=data;return{ok:true,id:'new'}};b.kwOpenRun=async()=>{};b.kwLoad=async()=>{};
 await b.kwStart();assert.equal(sent.slots.length,1);assert.equal(sent.sample,20);assert.equal(sent.blind,false);
 b.kwChooseMode('compare');b.kwCount=3;b.kwSample=2;await b.kwStart();assert.equal(sent.slots.length,3);assert.equal(sent.sample,2);assert.equal(sent.blind,true);
 b.kwCreateVersion(1);assert.equal(b.kwTab,'prompts');assert.equal(b.kwDraft.model,'m2');
 b.kwRequest=async()=>({ok:true,version:{id:'new-v',model:'m2',number:1,rules:'new rules',title:'new'}});
 await b.kwSaveVersion();assert.equal(b.kwTab,'run');assert.equal(b.kwSlots[1].version_id,'new-v');assert.equal(b.kwDraftSlot,null);
 const c=window.PRISM_APP_PARTS[0]();c.kwRunData={id:'old'};c.kwReview={};await c.kwOpenRun('');assert.equal(c.kwRunData,null);assert.equal(c.kwReview,null);
 b.kwCatalog.rules_by_target={keyword:'keyword rules',sentence:'preserved sentence rules'};
 b.kwTargetChange('sentence');assert.equal(b.kwDraft.rules,'preserved sentence rules');assert.equal(b.kwSlots[0].version_id,'');assert.equal(b.kwRunData,null);
 b.kwChooseMode('single');b.kwSlots[0]={model:'m1',version_id:'sv1'};b.kwLead='리드문';b.kwEntities='';b.kwSource='direct';
 assert.equal(b.kwReady(),false);b.kwSentenceKeywords='한국은행';assert.equal(b.kwReady(),true);
 b.kwRequest=async(q,data)=>{sent=data;return{ok:true,id:'sentence-run'}};
 await b.kwStart();assert.equal(sent.target,'sentence');assert.equal(sent.keyword_source,'manual');assert.equal(sent.keywords[0],'한국은행');
 b.kwRunData={target:'sentence',cells:{'s:A':{id:'s:A',status:'failed',review_revision:0,sentence:{draft:'긴 문장 초안'},reviews:[]}}};
 b.kwOpenReview({key:'s'},{label:'A'});assert.equal(b.kwReview.target,'sentence');assert.equal(b.kwReview.judgments[0].original,'긴 문장 초안');assert.equal(b.kwTab,'run');
 // 상세 검수: 다음 콘텐츠는 같은 조합 우선 · 실패 셀 건너뜀 · 저장 후 다음 미검수 · 삭제 시 선택값 정리
 const d=window.PRISM_APP_PARTS[0]();d.kwCatalog={versions:[],gold:[]};
 const cell=(id,status,reviews)=>({id,status,review_revision:0,refined:{keywords:[{text:'한국은행 금리',kind:'combo'}]},reviews,final:null});
 const it=[{key:'i1'},{key:'i2'},{key:'i3'}],sl=[{label:'A'},{label:'B'}];
 d.kwRunData={items:it,slots:sl,cells:{'i1:A':cell('i1:A','done',[]),'i1:B':cell('i1:B','done',[]),'i2:A':cell('i2:A','failed',[]),'i2:B':cell('i2:B','done',[{judgments:[{verdict:'accept',reason:'',corrected:'한국은행 금리'}],additions:[],no_keywords:false,note:''}]),'i3:B':cell('i3:B','done',[])}};
 d.kwOpenReview(it[0],sl[1]);assert.equal(d.kwReviewGo(1),true);assert.equal(d.kwReview.cell_id,'i2:B');
 d.kwOpenReview(it[0],sl[0]);d.kwReviewGo(1);assert.equal(d.kwReview.cell_id,'i2:B');assert.equal(d.kwReviewGo(-1),true);assert.equal(d.kwReview.cell_id,'i1:B');
 assert.equal(d.kwNextPending(),true);assert.equal(d.kwReview.cell_id,'i3:B');d.kwNextPending();assert.equal(d.kwReview.cell_id,'i1:A');
 assert.equal(d.kwSlotState(d.kwRunData.cells['i2:A']),'실패');assert.equal(d.kwInKeywords('한국은행'),true);assert.equal(d.kwInKeywords('물가'),false);
 d.kwVersion={id:'v9',model:'solar',number:2,title:'t'};d.kwSlots[0].version_id='v9';d.kwLoopVersion='v9';d.kwCatalog.active={};
 d.kwRequest=async(q,data)=>{sent=data;return{ok:true}};d.kwLoad=async()=>{};const confirm0=window.confirm;window.confirm=()=>true;
 await d.kwDeleteVersion();window.confirm=confirm0;assert.equal(sent.action,'delete');assert.equal(d.kwSlots[0].version_id,'');assert.equal(d.kwLoopVersion,'');assert.equal(d.kwVersion,null);
 d.kwCatalog.active={m:{version_id:'v1'}};assert.equal(d.kwAdopted({id:'v1'}),true);
 // 결과 목록: 콘텐츠 상태 · 행 클릭은 판정 안 한 조합부터
 assert.deepEqual(d.kwItemState(it[0])[0],'미검수');assert.equal(d.kwItemState(it[1])[0],'판정됨');
 d.kwRunData.cells['i3:A']=cell('i3:A','failed',[]);assert.equal(d.kwItemState(it[2])[0],'미검수');
 d.kwRunData.cells['i1:A'].reviews=[{judgments:[{verdict:'accept',reason:'',corrected:'x'}],additions:[],no_keywords:false,note:''}];
 assert.equal(d.kwItemState(it[0])[0],'검수 중');d.kwOpenItem(it[0]);assert.equal(d.kwReview.cell_id,'i1:B');
 d.kwRunData.cells['i2:B'].final={};assert.equal(d.kwItemState(it[1])[0],'확정');
 delete d.kwRunData.cells['i3:B'];assert.equal(d.kwItemState(it[2])[0],'대기');
 console.log('Keyword workspace client: required selection, review identity, revision and failures passed');
}
main().catch(e=>{console.error(e);process.exitCode=1});
